name: Resume Review
description: Please review and give feedback on my resume
title: "[REVIEW]"
labels: [resume review]
body:
  - type: markdown
    attributes:
      value: "**Redact all personal data**"
  - type: input
    id: link
    attributes:
      label: Resume link
      placeholder: "e.g.: https://drive.google.com/file/d/<file-id>/view"
    validations:
      required: true
